---
driver:
  name: ec2
  aws_ssh_key_id: <SSH KEY NAME>
  security_group_ids: ["<AWS SECURITY GROUP ID>"]
  region: us-east-1
  availability_zone: a
  require_chef_omnibus: true
  subnet_id: <AWS SUBNET ID>
  instance_type: m3.medium
  associate_public_ip: true
  interface: dns

transport:
  ssh_key: ~/.ssh/<SSH KEY NAME>
  connection_timeout: 10
  connection_retries: 5
  username: ubuntu

platforms:
#  - name: ubuntu-14.04
#    driver:
#      image_id: ami-452bd728
#  - name: ubuntu-15.10
#    driver:
#      image_id: ami-3505ee58
#  - name: ubuntu-16.04
#    driver:
#      image_id: ami-13be557e
  - name: centos-7
    driver:
      image_id: ami-6d1c2007
    transport:
      username: centos
#  - name: amazonlinux-2016.03.2
#    driver:
#      image_id: ami-a4827dc9
#    transport:
#      username: ec2-user

suites:
  - name: default
    run_list:
      - recipe[aws_inspector::default]
    attributes:
    verifier:
      name: inspec
